name: flutter_widget_carousel
description: "Widget carousel feature, implemented purely in Flutter code."
version: 0.0.2
homepage: https://github.com/YBill/flutter_widget_carousel

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0